
# Application configuration
name: "rent_Montreal"
version: "0.1.0.0"

# Logging configuration
log_path: "data/log/rent_Montreal.log"
log_level: "INFO"
log_console: false
log_file: true

# Database configuration
db_name: "kijiji"
table_name: "rent_Montreal"
db_type: "mongodb"
connection_info: "mongodb://10.0.0.110:27017"

# Scrapper configuration
do_pagination: true 
do_completion: false

# Pagination configuration
pagination:
  base_url: "https://www.kijiji.ca/b-{category}/levis/page-{start_page}/{category-id}?address={address}&ll={latitude},{longitude}&radius={radius}&ad=offer&sort={sort}"
  start_page: 1
  max_zero_added: 2
  url_settings:
    category: 'apartments-condos'
    category-id : "c37l1700063"
    address: 'Côte-des-Neiges, Côte-Des-Neiges—Notre-Dame-De-Grâce, Montreal, QC'
    latitude: '45.4767847'
    longitude: '-73.61431329999999'
    radius: '5.0'
    sort: 'dateDesc'
